# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'etc'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "#{Dir.home}", "/mnt/synced/"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y language-pack-en
  SHELL
end
