# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'etc'

Vagrant.configure("2") do |config|
  config.vm.box = "vitalibo/ubuntu-20.04.2.0-desktop-amd64"
  config.vm.box_url = "file://packer/target/ubuntu-virtualbox.box"
  config.vm.synced_folder "#{Dir.home}", "/mnt/synced/"

  config.ssh.password = 'vagrant'

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "6144"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm", "--vram", "128"]
    vb.customize ["setextradata", :id, "GUI/ScaleFactor", "2.0"]
  end
end
